const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
const sourcePath=process.argv[2]||path.join(root,'index.html');
let html=fs.readFileSync(sourcePath,'utf8');
const base='https://jony1346.github.io/feelings-together.github.io/';
const description='A free emotion memory game for children ages 3–12 by Idit Edelshtein, CBT therapist and parent guide. Explore 30 feelings together, choose optional conversation prompts and print the cards at home.';
const elements={};
const ctx={window:{matchMedia:()=>({matches:true})},document:{body:{},createTreeWalker:()=>({nextNode:()=>false}),getElementById:id=>elements[id]||(elements[id]={setAttribute(){}}),querySelectorAll:()=>[]},NodeFilter:{SHOW_TEXT:4},clearInterval:()=>{}};
vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(root,'art-young-boy.js'),'utf8'),ctx);
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1].split('try{character=localStorage')[0];
vm.runInContext(script,ctx);
vm.runInContext("lang='en';renderHome();renderFooter();renderAccessibility();",ctx);
html=html.replace(/<dialog id="accessibilityPanel"[\s\S]*?<\/dialog>/,'<dialog id="accessibilityPanel" class="a11y-panel no-print" aria-labelledby="accessibilityTitle">'+elements.accessibilityPanel.innerHTML+'</dialog>');html=html.replace('aria-label="אפשרויות נגישות"','aria-label="Accessibility options"').replace('>דילוג לתוכן<','>Skip to content<');
const translations=vm.runInContext('translations',ctx);
const start=html.indexOf('<section id="home"'),end=html.indexOf('<section id="game"',start);
html=html.slice(0,start)+'<section id="home" class="screen active">'+elements.home.innerHTML+'</section>\n'+html.slice(end);
html=html.replace(/<footer id="siteFooter"[\s\S]*?<\/footer>/,'<footer id="siteFooter" class="site-footer no-print">'+elements.siteFooter.innerHTML+'</footer>');
const scriptStart=html.indexOf('<script src="art-young-boy.js');
const before=html.slice(0,scriptStart).replace(/>([^<>]+)</g,(full,text)=>translations[text]!==undefined?'>'+translations[text]+'<':full);
html=before+html.slice(scriptStart);
html=html.replace('<html lang="he" dir="rtl">','<html lang="en" dir="ltr">');
html=html.replace(/<title>.*?<\/title>/,'<title>Words for Feelings — Emotion Cards for Kids | Idit Edelshtein</title>');
html=html.replace(/(<meta (?:name|property)="(?:description|og:description|twitter:description)" content=")[^"]*(">)/g,(_,a,b)=>a+description+b);
html=html.replace(/(<meta (?:name|property)="(?:og:title|twitter:title)" content=")[^"]*(">)/g,(_,a,b)=>a+'Words for Feelings — Emotion Cards by Idit Edelshtein'+b);
html=html.replace('<meta name="author" content="עידית אדלשטיין">','<meta name="author" content="Idit Edelshtein">');
html=html.replace('<link rel="canonical" href="'+base+'">','<link rel="canonical" href="'+base+'en.html">');
html=html.replace('<meta property="og:url" content="'+base+'">','<meta property="og:url" content="'+base+'en.html">');
html=html.replace('<meta property="og:site_name" content="מילים לרגש">','<meta property="og:site_name" content="Words for Feelings">');
html=html.replace('<meta property="og:locale" content="he_IL">','<meta property="og:locale" content="en_US">').replace('<meta property="og:locale:alternate" content="en_US">','<meta property="og:locale:alternate" content="he_IL">');
html=html.replace(/(<meta property="og:image:alt" content=")[^"]*(">)/,(_,a,b)=>a+'Words for Feelings — Illustrated emotion cards for parents and children'+b);
html=html.replaceAll('share-preview-v4.png','share-preview-en-v1.png');
html=html.replace(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/,(_,json)=>{const schema=JSON.parse(json);schema['@graph'].forEach(item=>{if(['WebSite','WebApplication'].includes(item['@type'])){item.name='Words for Feelings';item.alternateName='מילים לרגש';item.description=description;item.inLanguage=item['@type']==='WebApplication'?'en':['he','en'];if(item['@type']==='WebApplication')item.url=base+'en.html'}if(item['@type']==='Person'){item.name='Idit Edelshtein';item.alternateName='עידית אדלשטיין';item.jobTitle=['CBT therapist','CBT facilitator','Parent guide'];item.url=base+'en.html#about'}if(item['@type']==='ImageObject')item.caption='Words for Feelings'});return '<script type="application/ld+json">'+JSON.stringify(schema)+'</script>'});
fs.writeFileSync(path.join(root,'en.html'),html);
console.log('English page generated with static localized search and sharing metadata.');
